"use client";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style jsx global>{`
          @import url("fonts/icomoon/style.css");
          @import url("fonts/flaticon/font/flaticon.css");
          @import url("css/tiny-slider.css");
          @import url("css/aos.css");
          @import url("css/style.css");
          @import url("https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap");
        `}</style>
      </head>

      <body>{children}</body>
    </html>
  );
}
